#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_1_TssA_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_2_TssAFlnk_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_3_TxFlnk_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_4_Tx_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_6_EnhG_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_7_Enh_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_8_ZNF.Rpts_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_9_Het_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_10_TssBiv_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_11_BivFlnk_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_12_EnhBiv_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_13_ReprPC_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_DNase_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_H3K27ac_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_Hypomethylated_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_Intermediate_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_Hypermethylated_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_Missing_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_5_TxWk_enriched.txt
#python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_14_ReprPCWk_enriched.txt
python ~/bin/TE_landscape/get_enriched_TEs.py enrichment/candidate_15_Quies_enriched.txt
