# For chromHMM and methylation states, creates matrices with
# 1) the frequency with which chromHMM states are shared on a TE within a single sample
# 2) the average number of samples a TE is annotated with each state, for those ever annotated with each state

## state_switching_intra - TE annotation with multiple chromHMM states in a single sample
## state_switching_inter - TE annotation with multiple states across samples, chromHMM, all TEs
## ss_inter_class - TE annotation with multiple states across samples, chromHMM, by class
## ss_inter_meth - TE annotation with multiple states across samples, methylation states, all TEs
## ss_inter_meth_class - TE annotation with multiple states across samples, chromHMM, by class


# TE annotation with multiple chromHMM states in a single sample
## For all instances of a TE x sample annotated with a chromHMM state (row), 
## The proportion of instances in which it is also annotated with another state (column)

# Load matrix of the number of instances where a TE in the row state is also annotated with the column state in the same sample
state_switching_intra = read.table("chromHMM/state_switching/rmsk_TEother_chromHMM_intra.txt",sep='\t',header=TRUE,row.names=1)

# Remove erroneous 15_Quies entry generated by python script (hardcode)
state_switching_intra[15,15] = state_switching_intra[15,15] - 1

# Replicate entries for State 1/State 2 as entries for State 2/State 1
state_switching_intra[lower.tri(state_switching_intra)] = t(state_switching_intra)[lower.tri(state_switching_intra)]

# Normalize each row by the total number of instances of a TE x sample in the state (diagonal)
for (i in 1:15){
  state_switching_intra[i,] = state_switching_intra[i,]/state_switching_intra[i,i]
}


# TE annotation with multiple states across samples, chromHMM, all TEs
## For TEs ever annotated with each state (row),
## The average number of samples in which they are annotated with each state (column)

# Load matrix of the total number of samples in which TEs are annotated with each chromHMM state (column)
# across all TEs annotated with each chromHMM state in any sample (row)
state_switching_inter = read.table("chromHMM/state_switching/rmsk_TEother_chromHMM_inter.txt",sep='\t',header=TRUE,row.names=1)

# Normalize each row by the number of TEs ever in the state
for (i in 1:15){
  state_switching_inter[i,] = state_switching_inter[i,]/apply(chromHMM_TE_state_dist[,2:16],2,function(x) sum(x[2:128]))[i]
}


# TE annotation with multiple states across samples, chromHMM, by class

# Load matrices of the total number of samples in which TEs are annotated with each chromHMM state (column)
# across all TEs annotated with each chromHMM state in any sample (row), by class
ss_inter_class = lapply(list.files(path="chromHMM/state_switching/class",pattern="rmsk_TEother",full.names=TRUE),
                        function(x) read.table(x,sep='\t',header=TRUE,row.names=1))
names(ss_inter_class) = c("DNA","LINE","LTR","Other","SINE","SVA")

# For each class matrix, normalize each row by the number of TEs ever in the state
for (j in 1:6){
 for (i in 1:15){
   ss_inter_class[[j]][i,] = ss_inter_class[[j]][i,]/
     apply(chromHMM_TE_state_class[which(chromHMM_TE_state_class$class_update == names(ss_inter_class)[j]),3:17],2,function(x) sum(x[2:128]))[i]
 }
}

# Combine class matrices
ss_inter_class = ldply(ss_inter_class,.id="Class")
ss_inter_class$State = rep(chromHMM_states,6)
ss_inter_class$Class = factor(ss_inter_class$Class,levels=c("DNA","LINE","LTR","SINE","SVA","Other"))


# TE annotation with multiple states across samples, methylation states, all TEs

# Load matrices of the total number of samples in which TEs are annotated with each methylation state (column)
# across all TEs annotated with each methylation state in any sample (row)
ss_inter_meth = read.table("WGBS/TE_WGBS_state_inter.txt",sep='\t',header=TRUE,row.names=1)
ss_inter_meth = ss_inter_meth[meth_states,meth_states]

# Normalize each row by the number of TEs ever in the state
for (i in 1:4){
  ss_inter_meth[i,] = ss_inter_meth[i,]/apply(TE_meth_average_category[,meth_states],2,function(x) sum(x[2:38]))[i]
}


# TE annotation with multiple states across samples, methylation states, by class

# Load matrices of the total number of samples in which TEs are annotated with each methylation state (column)
# across all TEs annotated with each methylation state in any sample (row), by class
ss_inter_meth_class = lapply(list.files(path="WGBS/class",pattern="WGBS_state_sorted.txt_inter.txt",full.names=TRUE),
                             function(x) read.table(x,sep='\t',header=TRUE,row.names=1))
names(ss_inter_meth_class) = c("DNA","LINE","LTR","Other","SINE","SVA")

# For each class matrix, normalize each row by the number of TEs ever in the state
for (j in 1:6){
  ss_inter_meth_class[[j]] = ss_inter_meth_class[[j]][meth_states,meth_states]
  for (i in 1:4){
    ss_inter_meth_class[[j]][i,] = ss_inter_meth_class[[j]][i,]/
      apply(TE_meth_average_class[which(TE_meth_average_class$class_update == names(ss_inter_meth_class)[j]),meth_states],2,function(x) sum(x[2:38]))[i]
  }
}

# Combine class matrices
ss_inter_meth_class = ldply(ss_inter_meth_class,.id="Class")
ss_inter_meth_class$State = rep(meth_states,6)
ss_inter_meth_class$Class = factor(ss_inter_meth_class$Class,levels=c("DNA","LINE","LTR","SINE","SVA","Other"))
